### ISSUE TITLE
Add providers

### ISSUE THREAD

**Issue by JulianKahnert** [allthingsdns/allthingsdns#2]
Add provider(s) maybe start with cloudflare and let's use the discussed "meta-class".

**Comment by Ethaligan** [comment]
- [ ] Cloudflare (https://api.cloudflare.com/)
- [ ] LiveDNS (Gandi) (https://doc.livedns.gandi.net/)

Feel free to add more :wink:

**Comment by JulianKahnert** [comment]
- [ ] Namecheap

...asking for a friend 😂

**Comment by JulianKahnert** [comment]
first one added in #9 others in #25 and #26
